app:
  name: leora-backend
  env: local
  port: 9090
  basePath: /api/v1
  jwtSecret: changeme
  jwtAccessTTL: 168h
  jwtRefreshTTL: 24h
  googleOAuthClient: "195986755853-qopo6nfnngllgg3e4aip4ccegthd37bq.apps.googleusercontent.com"
  appleBundleID: "com.sarvar.leora"

database:
  host: postgres
  port: 5432
  user: leora
  password: leora
  name: leora_dev

redis:
  addr: redis:6379
  password: ""
  db: 0
